kmeans:
  n_clusters: ${num_clusters}
  n_init: 100
  random_state: ${random_state}
kmedians:
  n_clusters: ${num_clusters}
  n_init: 100
  random_state: ${random_state}
spectral_clustering:
  n_clusters: ${num_clusters}
  eigen_solver: arpack
  affinity: nearest_neighbors
  random_state: ${random_state}
ward:
  n_clusters: ${num_clusters}
  n_neighbors: 7
  linkage: ward
agglomerative:
  n_clusters: ${num_clusters}
  n_neighbors: 5
  metric: cosine
  linkage: complete
# dbscan:
#   eps: 0.75
dbscan:
  eps: 0.88
  min_samples: 13
hdbscan:
  min_samples: 3
  min_cluster_size: 15
optics:
  min_samples: 5
  xi: 0.05
  min_cluster_size: 0.25
birch:
  n_clusters: ${num_clusters}
  threshold: 1.3
gaussian:
  n_components: ${num_clusters}
  covariance_type: full
  random_state: ${random_state}
